<a href="https://colab.research.google.com/github/TKhahahah/Data_Mining_FinalProject/blob/main/DTM_PJ1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Load Data

In [5]:
import pandas as pd
import os, sys

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
X_index = pd.read_csv('/content/drive/MyDrive/KKU3/X_variable(Index)_operation_v4.csv')
Y_rainfall = pd.read_csv('/content/drive/MyDrive/KKU3/Y_variable(Rainfall).csv')
# Convert 'DATE' column in Y_df to datetime objects if it's not already
X_index['DATE'] = pd.to_datetime(X_index['DATE'])

# Format the dates in Y_df as 'YYYY-MM-01'
X_index['DATE'] = X_index['DATE'].dt.strftime('%Y-%m-01')



node = pd.read_csv('/content/drive/MyDrive/KKU3/Node_table_TMD.csv')


path_feature = os.path.join("/content/drive/MyDrive/KKU3/lookup_table_reanalysis_v5.csv")
feature = pd.read_csv(path_feature, header= "infer")

In [8]:
X_index.head()

,DATE,MEIV2,RMM_AMPLITUDE,PHASE,BSISO1,BSISO1-Phase,DMI,ONI,PDO,SWM,NE
0,1981-01-01,0.35,1.79134,7.0,0.000,0.0,NaN,NaN,NaN,NaN,NaN
1,1981-02-01,0.23,2.04364,7.0,0.000,0.0,NaN,NaN,NaN,NaN,NaN
2,1981-03-01,0.33,3.16988,3.0,0.000,0.0,NaN,NaN,NaN,NaN,NaN
3,1981-04-01,0.42,3.22159,4.0,0.000,0.0,NaN,NaN,NaN,NaN,NaN
4,1981-05-01,0.24,0.00000,1.0,1.467,8.0,NaN,NaN,NaN,NaN,NaN

In [9]:
Y_rainfall.head()

,DATE,300201,300202,303201,303301,310201,327202,327301,327501,328201,...,566202,567201,568301,568401,568501,568502,570201,580201,581301,583201
0,1961-01-01,0.5,13.1,0.4,NaN,NaN,NaN,NaN,1.8,0.4,...,NaN,71.2,NaN,NaN,58.5,NaN,NaN,NaN,NaN,193.6
1,1961-02-01,1.1,4.4,5.7,NaN,NaN,NaN,NaN,33.3,2.4,...,NaN,89.9,NaN,NaN,13.2,NaN,NaN,NaN,NaN,76.7
2,1961-03-01,7.6,0.0,37.7,NaN,NaN,NaN,NaN,22.5,46.2,...,NaN,62.1,NaN,NaN,5.4,NaN,NaN,NaN,NaN,24.5
3,1961-04-01,94.6,27.1,118.8,NaN,NaN,NaN,NaN,65.2,58.6,...,NaN,124.1,NaN,NaN,154.9,NaN,NaN,NaN,NaN,42.3
4,1961-05-01,223.9,189.5,257.9,NaN,NaN,NaN,NaN,249.8,240.9,...,NaN,219.7,NaN,NaN,114.8,NaN,NaN,NaN,NaN,80.7

In [14]:
Y_rainfall.columns

Index(['DATE', '300201', '300202', '303201', '303301', '310201', '327202',
       '327301', '327501', '328201',
       ...
       '566202', '567201', '568301', '568401', '568501', '568502', '570201',
       '580201', '581301', '583201'],
      dtype='object', length=133)

In [10]:
node.head()

     Node        Lat       Long  cluster  quality  lag
0  300201  19.299814  97.972734      7.0        1  NaN
1  300202  18.176442  97.930608      7.0        1  NaN
2  303201  19.961219  99.881294      7.0        1  NaN
3  303301  19.871839  99.779203      7.0        1  NaN
4  310201  19.192933  99.883650      NaN        0  NaN

In [13]:
feature.head()

   Cluster Node   Lat   Long  quality  lag
0        1  SWM   0.0  101.0        0    0
1        1  DMI   0.0   80.0        1    1
2        1  PDO   0.0  165.0        1    1
3        1  ONI   0.0  180.0        0    0
4        1   NE  10.0  110.0        1    0

# Cleansing